inherit_from:
  - https://raw.githubusercontent.com/bbatsov/rubocop/master/config/enabled.yml

AllCops:
  Include:
    - '**/Rakefile'
  Exclude:
    - 'db/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
