language: ruby
rvm:
  - 2.3.4
dist: trusty
sudo: false
before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.27.5
  - export PATH=$HOME/.yarn/bin:$PATH
  - pip3 install https://github.com/sul-cidr/histonets-cv/archive/master.zip
  - RAILS_ENV=test bundle exec rake db:migrate
  - RAILS_ENV=test bundle exec rake assets:precompile
cache:
  yarn: true
# sudo: false Leaving this commented out, as we may need this to install the correct python version etc.
