language: ruby
rvm:
  - 2.3.4
dist: trusty
sudo: required
python:
  - "3.5"
before_script:
  - sudo apt-get update
  - sudo apt-get -y install python3-pip python-dev
  - python --version
  - python3 --version
  - pip --version
  - pip3 --version
  - sudo pip3 install https://github.com/sul-cidr/histonets-cv/archive/master.zip
  - RAILS_ENV=test bundle exec rake db:migrate
  - RAILS_ENV=test bundle exec rake assets:precompile
# sudo: false Leaving this commented out, as we may need this to install the correct python version etc.
